### ISSUE TITLE
In "init.org" what org-babel-tangle refers to? 

### ISSUE THREAD

**Issue by fedor-goncharov** [fedor-goncharov/emacs-tutorial#1]
@JuanGarcia345 Now I know that "org" is a type of format for "literal programming" within emacs. But I don't get the phrase: 

"Tangle file to generate Emacs configuration" + "M-x org-babel-tangle"

If I understood well from the man, this command should take source code from your "org" file and put it to a 
bunch of source code files... Tell me, if I am wrong. If I am not wrong, then I don't understand why this called "Emacs configuration files"?

Maybe a use example is needed. I tried to run this command withing "init.org" and it returned me some error....

**Comment by JuanGarcia345** [comment]
@fedor-goncharov, you got it right, "tangling" will put source code from Org file into source files.

In this case, calling the function `org-babel-tangle` will extract blocks in:
-  [line 17](https://github.com/fedor-goncharov/emacs-tutorial/blob/main/init.org#L17)
-  [line 22](https://github.com/fedor-goncharov/emacs-tutorial/blob/main/init.org#L22)
-  [line 39](https://github.com/fedor-goncharov/emacs-tutorial/blob/main/init.org#L39)
-  [line 51](https://github.com/fedor-goncharov/emacs-tutorial/blob/main/init.org#L51)

and put them in the file `init.el`, the former is an Emacs lisp file usually used as [configuration file](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html).  When Emacs starts, it will load (execute) this file but only if it's located in directory `~/.emacs.d/`

So the real configuration is the one in file `init.el` and this file is generated from file `init.org` by executing `M-x org-babel-tangle`. 

Do you mind to describe the error generated when you execute this command? There is `buffer` called `*Messages*` where errors are also printed (to change buffer you may use the menu *Buffers* in the menu bar or the command `C-x b *Messages* RET`).

Also, it's worth notice that the link "[configuration file](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html)" points to the Emacs 28 manual, to avoid any confusion I may recommend to use the Info documentation from your Linux, the version will be the good one. To do so, you can type:
- `C-h i RET`
- `m Emacs RET`
- `m Init File RET`

The first command enters a mode to browse manuals, the next commands are only to chose the right documentation entries.

**Comment by fedor-goncharov** [comment]
There is no problem, since I didn't know that I had to execute the command inside the init.org (error was due to this) :)
